export const WORKOUT_TOKENS = {
  primary: '#b1c5ff',
  tertiary: '#59d8de',
  surface: '#111318',
  surfaceLow: '#161820',
  surfaceContainer: '#1e2026',
  surfaceHigh: '#282a30',
  outline: '#8e909c',
  outlineVariant: '#3a3c44',
  onSurface: '#e2e2e8',
  onSurfaceVariant: '#c5c6d2',
  cardRadius: 16,
  inputRadius: 10,
  cardPadding: 16,
  cardGap: 12,
  exerciseName: {
    fontFamily: 'Space Grotesk, sans-serif',
    fontWeight: 800,
    fontSize: '0.95rem',
  },
  metadata: {
    fontFamily: 'Manrope, sans-serif',
    fontWeight: 500,
    fontSize: '0.65rem',
    letterSpacing: '0.14em',
    textTransform: 'uppercase' as const,
  },
  fieldLabel: {
    fontFamily: 'Manrope, sans-serif',
    fontWeight: 700,
    fontSize: '0.55rem',
    letterSpacing: '0.16em',
    textTransform: 'uppercase' as const,
  },
  input: {
    fontFamily: 'Space Grotesk, sans-serif',
    fontWeight: 800,
    fontSize: '1rem',
    textAlign: 'center' as const,
    background: '#161820',
    border: '1px solid #3a3c44',
    borderRadius: 10,
    padding: '10px 8px',
  },
};
